"""row instead of col

Revision ID: 4de9d5f1221d
Revises: 8a82e9684e95
Create Date: 2024-11-07 22:29:07.803951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de9d5f1221d'
down_revision: Union[str, None] = '8a82e9684e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('csv_rows', sa.Integer(), nullable=True))
    op.drop_column('files', 'csv_columns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('csv_columns', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('files', 'csv_rows')
    # ### end Alembic commands ###
