"""Create initial users

Revision ID: be954dcdea5b
Revises: 4de9d5f1221d
Create Date: 2024-11-09 18:10:58.733059

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import insert
from app.auth import bcrypt_context
from app.db.models import User


# revision identifiers, used by Alembic.
revision: str = 'be954dcdea5b'
down_revision: Union[str, None] = '4de9d5f1221d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        insert(User).values(
            email='user1@gmail.com',
            password=bcrypt_context.hash("password1"),
        )
    )
    op.execute(
        insert(User).values(
            email='user2@gmail.com',
            password=bcrypt_context.hash("password2"),
        )
    )
    op.execute(
        insert(User).values(
            email='user3@gmail.com',
            password=bcrypt_context.hash("password3"),
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
